<?php

//handy-dandy date & time functions by rjr // inkplant.com

function dateBoxes($stime=null,$blankdate=false,$beginyear=null,$endyear=null,$prefix=null,$suffix=null,$disabled=false,$js=null) {
    if ($stime > 2200) {
        $smonth = date("n", $stime) ;
        $sday = date("j", $stime) ;
        $syear = date("Y", $stime) ;
    } elseif (!$blankdate) {
        $smonth = date("n") ;
        $sday = date("j") ;
        $syear = date("Y") ;
    } elseif (($stime > 1800) && ($stime < 2200)) { //year only
        $smonth = false;
        $sday = false;
        $syear = $stime;
    } else {
        $smonth = false;
        $sday = false;
        $syear = false;
    }
    if ($disabled) { $disabled = ' disabled'; } else { $disabled = '' ; }
    $yearbox = "<select name=\"".$prefix."y".$suffix."\" id=\"".$prefix."y".$suffix."\" size=1".$js.$disabled.">" ;
    if ($blankdate) { $yearbox .= "<option value=\"\"></option>" ; }
    if (!$beginyear) { $beginyear = 1970; }
    if (!$endyear) { $endyear = 2030; }
    $y = $beginyear;
    while ($y <= $endyear) {
        if ($y == $syear) { $selected = " selected" ; } else { $selected = "" ; }
        $yearbox .= "<option value=\"$y\"".$selected.">$y</option>" ;
        $y++;
    }
    $yearbox .= "</select>" ;
    $monthbox = "<select name=\"".$prefix."m".$suffix."\" id=\"".$prefix."m".$suffix."\" size=1".$js.$disabled.">" ;
    if ($blankdate) { $monthbox .= "<option value=\"\"></option>" ; }
    for ($m=1; $m<=12; $m++) {
        $mtime = mktime(0,0,0,$m,15,2009);
        if ($m == $smonth) { $selected = " selected" ; } else { $selected = "" ; }
        $monthbox .= "<option value=\"".date('m',$mtime)."\"".$selected.">".date('M',$mtime)."</option>" ;
    }
    $monthbox .= "</select> " ;
    $daybox = "<select name=\"".$prefix."d".$suffix."\" id=\"".$prefix."d".$suffix."\" size=1".$js.$disabled.">" ;
    if ($blankdate) { $daybox .= "<option value=\"\"> </option>" ; }
    for ($d=1; $d<=31; $d++) {
        $dtime = mktime(0,0,0,1,$d,2009);
        if ($d == $sday) { $selected = " selected" ; } else { $selected = "" ; }
        $daybox .= "<option value=\"".date('d',$dtime)."\"".$selected.">$d</option>" ;
    }
    $daybox .= "</select> " ;
    $dateboxes = $monthbox.$daybox.$yearbox;
    return $dateboxes;
}

function timeBox($stime=null,$prefix=null,$suffix=null,$disabled=false,$include_seconds=false) {
    if ($stime > 0) {
        if (($include_seconds) && (date('s',$stime) > 0)) { $format = 'g:i a'; } else { $format = 'g:i a'; }
        $value = date($format,$stime);
    } else { $value = ''; }
    return "<input type=\"text\" name=\"".$prefix."t".$suffix."\" value=\"$value\" title=\"Time of Day, ex. ".date('g:i a')."\" size=5 maxlength=10 $disabled />" ;
}

function getDateBoxesTime($prefix=null,$suffix=null,$timebox=false) {
    global $warnings;
    if (!is_array($warnings)) { $warnings = array(); }
    if (!$_REQUEST[$prefix.'m'.$suffix]) { return false; }
    if (!$_REQUEST[$prefix.'d'.$suffix]) { return false; }
    if (!$_REQUEST[$prefix.'y'.$suffix]) { return false; }
    $m = intval($_REQUEST[$prefix.'m'.$suffix]);
    $d = intval($_REQUEST[$prefix.'d'.$suffix]);
    $y = intval($_REQUEST[$prefix.'y'.$suffix]);
    if ($m == 0) { return false; }
    if ($d == 0) { return false; }
    if ($y == 0) { return false; }
    $time = mktime(0,0,0,$m,$d,$y);
    if ($timebox) {
        $t = strip_tags($_REQUEST[$prefix.'t'.$suffix]);
        if ($t) {
            $oldtime = $time;
            $time = strtotime(date('n/j/y',$time).' '.$t);
            if (!$time) {
                $time = $oldtime;
                $warnings[] = "The time of day <em>".htmlspecialchars($t)."</em> was not understood." ;
            }
        } else { $warnings[] = "No time of day was entered." ; }
    }
    return $time;
}

//this is handy for comparing dates to those generated by getDateBoxesTime()
function noonToday() {
    $m = date('n');
    $d = date('j');
    $y = date('Y');
    $time = mktime(12,0,0,$m,$d,$y);
    return $time;
}

?>